<a href="https://colab.research.google.com/github/sril1485/CE888/blob/master/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
<class 'numpy.ndarray'>
int64
2
(4, 2)


In [3]:
arr=np.array([[111,211,130,401,15,61,17,81,19,110]])
print(np.sort(arr))
b=np.sort(arr)
print(type(b))
print(b[::,::-1])

[[ 15  17  19  61  81 110 111 130 211 401]]
<class 'numpy.ndarray'>
[[401 211 130 111 110  81  61  19  17  15]]


In [4]:
one_d=np.array([1,2,3,4,5,6,7,8,9])
two_d=np.array([[one_d[0:3]],[one_d[3:6]],[one_d[6:]]])
print(two_d)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [5]:
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
v_arr=np.array([arr_1,arr_2])
print(v_arr)
h_arr=np.concatenate([arr_1,arr_2])
print(h_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [6]:
ar_1=np.array([1,2,3])
ar_2=np.array([3,5,6])
s_ar1=set(ar_1)
s_ar2=set(ar_2)
s_ar1.intersection(s_ar2)

{3}

In [7]:
fiv_ar=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
#print(fiv_ar.shape)
print('Min')
for i in fiv_ar:
  print(min(i))
print('\n')
for i in fiv_ar.T:
  print(min(i))
print('Max')
for i in fiv_ar:
  print(max(i))
print('\n')
for i in fiv_ar.T:
  print(max(i))

Min
1
6
11
16
21


1
2
3
4
5
Max
5
10
15
20
25


21
22
23
24
25


In [8]:
from numpy.random import rand
stat=np.array(rand(100))
print('mean:')
print(np.mean(stat))
print('median:')
print(np.median(stat))
print('standard deviation:')
print(np.std(stat))

mean:
0.43523556275030884
median:
0.3787505439665961
standard deviation:
0.27961590348253884


In [9]:
from sklearn.decomposition import PCA

from sklearn.preprocessing import normalize
fiv_ar=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
normed_matrix = normalize(fiv_ar, axis=1)
print(normed_matrix)

[[0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]
 [0.33028913 0.38533732 0.44038551 0.49543369 0.55048188]
 [0.37619206 0.41039134 0.44459062 0.4787899  0.51298918]
 [0.39630192 0.42107079 0.44583966 0.47060853 0.4953774 ]
 [0.40755576 0.42696317 0.44637059 0.46577801 0.48518542]]


In [10]:
mat_try=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
                  [[13,14,15],[16,17,18],[19,20,21],[22,23,24]],
                  [[25,26,27],[28,29,30],[31,32,33],[34,35,36]],
                  [[37,38,39],[40,41,42],[44,45,46],[47,48,49]]])

four_a=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,1,2],
                [3,4,5,6]])
print(np.matmul(four_a,mat_try))

[[[  70   80   90]
  [ 158  184  210]
  [  36   48   60]
  [ 114  132  150]]

 [[ 190  200  210]
  [ 470  496  522]
  [ 180  192  204]
  [ 330  348  366]]

 [[ 310  320  330]
  [ 782  808  834]
  [ 324  336  348]
  [ 546  564  582]]

 [[ 437  447  457]
  [1109 1135 1161]
  [ 471  483  495]
  [ 773  791  809]]]
