<a href="https://colab.research.google.com/github/sril1485/CE888/blob/master/lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [0]:
data = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/user_ratings.csv")

In [0]:
n_latent_factors = 2

user_ratings = data.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [4]:
latent_item_features


array([[0.741, 0.084],
       [0.707, 0.626],
       [0.126, 0.645],
       [0.298, 0.452],
       [0.913, 0.549]])

In [5]:
latent_user_preferences


array([[0.945, 0.325],
       [0.307, 0.251],
       [0.259, 0.49 ],
       [0.053, 0.903],
       [0.454, 0.793],
       [0.44 , 0.17 ],
       [0.593, 0.694],
       [0.812, 0.015],
       [0.387, 0.448],
       [0.841, 0.621]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=1000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print(mse)

In [12]:
sgd()

1.4367202141111393


In [13]:

predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.798,  1.406, -0.497,  5.346,  4.079],
       [ 3.514,  2.531,  9.778,  5.879,  7.395],
       [ 7.873,  2.6  ,  5.721,  7.557,  7.575],
       [ 8.193,  2.937,  7.173,  8.287,  8.561],
       [ 1.478,  1.872,  8.369,  3.949,  5.475],
       [ 2.283,  1.449,  5.321,  3.462,  4.231],
       [ 3.316,  1.811,  6.181,  4.491,  5.286],
       [ 8.275,  2.2  ,  3.205,  6.968,  6.402],
       [ 3.717,  1.759,  5.504,  4.54 ,  5.134],
       [ 3.003,  1.38 ,  4.228,  3.592,  4.026]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

In [15]:

comparison_data

The Call of Cthulhu  ...              Space Odyssey
0   (8.0, 7.798100588912573)  ...    (4.0, 4.07903428107082)
1   (3.0, 3.513611084661923)  ...   (7.0, 7.394626443537732)
2   (9.0, 7.873225876245922)  ...   (5.0, 7.575359969844888)
3    (nan, 8.19276267527872)  ...   (9.0, 8.560624043360434)
4  (nan, 1.4781798324457358)  ...   (7.0, 5.474901027719156)
5  (2.0, 2.2828773872212613)  ...  (nan, 4.2311978306738425)
6   (4.0, 3.315808956508669)  ...   (7.0, 5.285895298806231)
7   (7.0, 8.275398098554046)  ...   (9.0, 6.401871764980757)
8  (3.0, 3.7169801741529636)  ...   (3.0, 5.133531970752895)
9  (4.0, 3.0030664263863898)  ...   (3.0, 4.026229289942425)

[10 rows x 5 columns]